// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PasswordReset', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PasswordReset', async function() {
    await driver.get("http://localhost:3000/loginorreg")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Signup")).click()
    {
      const element = await driver.findElement(By.linkText("Signup"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("Hiruna")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("desilvahiruna72@gmail.com")
    await driver.findElement(By.name("mobileNumber")).click()
    await driver.findElement(By.name("mobileNumber")).sendKeys("0764231391")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("Rsm@1234")
    await driver.findElement(By.name("repeatPassword")).sendKeys("Rsm@1234")
    await driver.findElement(By.css(".sc-qZrbh")).click()
    {
      const element = await driver.findElement(By.css(".sc-qZrbh"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".sc-qZrbh")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("desilvahiruna72@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("rsm@1234")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    await driver.close()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("desilvahiruna72@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("rsm@1234")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".sc-qZrbh")).click()
    await driver.findElement(By.css(".hDpctm > svg")).click()
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.linkText("Reset it")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("hirunadesilva0422@gmail.com")
    await driver.findElement(By.css(".sc-qZrbh")).click()
  })
})
